name: Alnawawi Automation
on:
  schedule:
    - cron: '0 5 * * *'  # Runs at 5AM UTC daily
  workflow_dispatch:  # Allow manual runs

jobs:
  automate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          GDRIVE_CREDS: ${{ secrets.GDRIVE_CREDS }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
        run: python alnawawi_automation.py

      - name: Archive logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: output-logs
          path: |
            *.log
            *.csv
